// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw3koCLKQ1S3jdrLC_eTqlsa5Es8HXKTE',
    appId: '1:563439771466:web:752ad5b97d44a5b1956bb3',
    messagingSenderId: '563439771466',
    projectId: 'no-bolso-mobile',
    authDomain: 'no-bolso-mobile.firebaseapp.com',
    storageBucket: 'no-bolso-mobile.firebasestorage.app',
    measurementId: 'G-2TVBXD6CY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSisFlpZg31JTSd6elXb2nymgOuONMu7w',
    appId: '1:563439771466:android:a739ebb0621711d9956bb3',
    messagingSenderId: '563439771466',
    projectId: 'no-bolso-mobile',
    storageBucket: 'no-bolso-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB66TM123ZHXfzp5UksEtVe_Bw6wHepajQ',
    appId: '1:563439771466:ios:b2009e0954cd32ad956bb3',
    messagingSenderId: '563439771466',
    projectId: 'no-bolso-mobile',
    storageBucket: 'no-bolso-mobile.firebasestorage.app',
    iosBundleId: 'com.postech.nobolso.noBolsoMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB66TM123ZHXfzp5UksEtVe_Bw6wHepajQ',
    appId: '1:563439771466:ios:b2009e0954cd32ad956bb3',
    messagingSenderId: '563439771466',
    projectId: 'no-bolso-mobile',
    storageBucket: 'no-bolso-mobile.firebasestorage.app',
    iosBundleId: 'com.postech.nobolso.noBolsoMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw3koCLKQ1S3jdrLC_eTqlsa5Es8HXKTE',
    appId: '1:563439771466:web:8f411a967896e3ef956bb3',
    messagingSenderId: '563439771466',
    projectId: 'no-bolso-mobile',
    authDomain: 'no-bolso-mobile.firebaseapp.com',
    storageBucket: 'no-bolso-mobile.firebasestorage.app',
    measurementId: 'G-T99JED76MX',
  );
}
